services:
  progetto1:
    build:
      context: ./progetto1
    restart: unless-stopped
    init: true
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - app_network
  progetto2:
    build:
      context: ./progetto2
    restart: unless-stopped
    init: true
    ports:
      - "8082:80"
    depends_on:
      - db
    networks:
      - app_network
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app_db
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
volumes:
  db_data:
networks:
  app_network: